# MCBN-Shops Konfiguration
currency-material: DIAMOND
buy-mode: SNEAK_RIGHT_CLICK   # SNEAK_RIGHT_CLICK oder COMMAND_ONLY
look-range-blocks: 6
scoreboard:
  title: '&aMCBN &7Shop'
  enabled: true
bossbar:
  broadcast-interval-minutes: 15
  display-seconds-per-item: 5
  color: BLUE
  style: SEGMENTED_10
auctions:
  max-duration-hours: 72
  min-duration-minutes: 10
  allow-multiple-items: true
storage:
  autosave-minutes: 10

floating-item:
  enabled: true
  height: 1.2
  refresh-seconds: 5

shopkeepers:
  enabled: true

# Tutorial/Info-Broadcast-System
# ========================================
# API für externe Plugins:
# Das Plugin feuert ein "TutorialBroadcastEvent" bevor Tutorial-Nachrichten gesendet werden.
# Externe Plugins können dieses Event nutzen um:
#   1) Das Event zu canceln (event.setCancelled(true)) um ein eigenes Tutorial-System zu verwenden
#   2) Die Nachrichten zu modifizieren (event.setMessages(...)) bevor sie gesendet werden
#   3) Eigene Logik vor oder nach dem Broadcast auszuführen
#
# Wenn das Event gecancelt wird, sendet dieses Plugin KEINE Nachrichten.
# Das externe Plugin übernimmt dann die Verantwortung für die Tutorial-Anzeige.
#
# Beispiel Event-Handler für externe Plugins:
#   @EventHandler
#   public void onTutorial(TutorialBroadcastEvent event) {
#       event.setCancelled(true);  // Übernimmt Tutorial-System
#       // Eigene Logik hier
#   }
tutorial:
  # Aktiviert/Deaktiviert das Tutorial-Broadcast-System
  enabled: true

  # Intervall in Minuten zwischen den Broadcasts
  # Standard: 40 Minuten (kann von MCBNTabChat überschrieben werden)
  broadcast-interval-minutes: 40

  # Liste der Nachrichten, die gebroadcastet werden sollen
  # Unterstützt Minecraft Color-Codes mit '&' (z.B. &a = grün, &c = rot)
  # Diese Nachrichten werden auch an MCBNTabChat weitergegeben, falls vorhanden
  # Hinweis: Externe Plugins können diese Nachrichten über das Event modifizieren
  messages:
    - '&6&l━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━'
    - '&e&l     MCBN-Shops Tutorial'
    - '&6&l━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━'
    - ''
    - '&7&lWas kannst du hier machen?'
    - '&fMit MCBN-Shops kannst du eigene Shops erstellen,'
    - '&fGegenstände versteigern und Shopkeeper platzieren!'
    - ''
    - '&7&lWichtige Commands:'
    - '&8▸ &a/shop create &7- Erstelle einen neuen Shop'
    - '&8▸ &a/shop info &7- Zeigt Shop-Informationen'
    - '&8▸ &a/auction start &7- Starte eine Auktion'
    - '&8▸ &a/auction browse &7- Durchsuche Auktionen'
    - '&8▸ &a/shopkeeper create &7- Erstelle einen Shopkeeper (Villager)'
    - ''
    - '&7&lWie funktioniert ein Shop?'
    - '&8▸ &ePlatziere eine Truhe mit deinen Waren'
    - '&8▸ &eNutze &a/shop create &eund wähle die Truhe'
    - '&8▸ &eSetze Preis und Menge'
    - '&8▸ &eSpieler können mit &aShift + Rechtsklick &ekaufen'
    - ''
    - '&7&lWährung:'
    - '&8▸ &6Diamanten &7sind die Währung auf diesem Server'
    - ''
    - '&7&lTipps:'
    - '&8▸ &eAuktionen laufen bis zu 72 Stunden'
    - '&8▸ &eShopkeeper können mehrere Shops verwalten'
    - '&8▸ &eVergiss nicht deine Shops aufzufüllen!'
    - ''
    - '&6&l━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━'
    - '&7Viel Erfolg beim Handeln! &e/tutorial &7für mehr Infos'
    - '&6&l━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━'
